"""
    Pentagon numbers

    Problem 44

    Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""
import math


def is_pentagonal(p):
    p_root = (((1/2)+math.sqrt(1/4 + 6*p))/3)
    return p_root == int(p_root)


def pentify(n):
    return int(n * (3 * n - 1) / 2)


def generate_pent_list(size):
    return [pentify(i) for i in range(size)]



def get_minimal_pentagonal_difference_more_efficient():
    # j = 28869366176, k = 28870844753, j + k = 57740210929, k - j = 1478577
    # j = 34665956715, k = 34667441255, j + k = 69333397970, k - j = 1484540
    # j = 39043876676, k = 39045367191, j + k = 78089243867, k - j = 1490515
    # j = 41665750005, k = 41667246507, j + k = 83332996512, k - j = 1496502

    pent_count = 500000  # tested with pent_count = 500000
    pent_list = generate_pent_list(pent_count)

    p_diff_index = 1
    is_pair_found = False
    index_pair = (0, 0)
    counter = 0

    while not is_pair_found and p_diff_index < pent_count:
        p_diff = pent_list[p_diff_index]
        if p_diff_index % 100 == 0:
            print(f"checking min diff: {p_diff}")
        max_index_to_test = len(pent_list)
        test_index = 1
        while test_index < max_index_to_test:
            j = pent_list[test_index]
            k = j + p_diff

            if counter % 1000000 == 0:
                print(f"testing j = {j}, k = {k}, j + k = {j + k}, k - j = {k - j}")

            # NOTE : commented out pent_bool_list code to see if is_pentagonal() would work better

            if is_pentagonal(k) and is_pentagonal(j+k) and is_pentagonal(k-j):
            # if pent_bool_list[k] and pent_bool_list[j + k] and pent_bool_list[k - j]:
                index_pair = (test_index, custom_index(pent_list, lambda x: x == k))
                is_pair_found = True

            test_index += 1
            counter += 1

        p_diff_index += 1

    return index_pair, k-j


def get_minimal_pentagonal_difference():
    pent_count = 50000
    pent_list = generate_pent_list(pent_count)
    # pent_bool_list = [False] * (pent_list[-1] + 1)
    # for pent in pent_list:
    #     pent_bool_list[pent] = True

    print(f"some pent numbers: {pent_list[:20]}")

    p_diff = 1  # 119000 tested up to
    is_pair_found = False
    index_pair = (0, 0)
    counter = 0

    while not is_pair_found and p_diff < 166000:
        if p_diff % 10 == 0:
            print(f"checking min diff: {p_diff}")
        max_index_to_test = int(p_diff/3)
        test_index = 1
        while test_index < max_index_to_test:
            j = pent_list[test_index]
            k = j + p_diff

            if counter % 10000 == 0:
                print(f"testing j = {j}, k = {k}, j + k = {j + k}, k - j = {k - j}")

            # NOTE : commented out pent_bool_list code to see if is_pentagonal() would work better

            if is_pentagonal(k) and is_pentagonal(j+k) and is_pentagonal(k-j):
            # if pent_bool_list[k] and pent_bool_list[j + k] and pent_bool_list[k - j]:
                index_pair = (test_index, custom_index(pent_list, lambda x: x == k))
                is_pair_found = True

            test_index += 1
            counter += 1

        p_diff += 1

    return index_pair, k-j


def custom_index(ls, f):
    return next((i for i, e in enumerate(ls) if f(e)), -1)


def main():
    index_pair, answer = get_minimal_pentagonal_difference_more_efficient()
    print(f"index pair {index_pair}")
    print(f"The Answer to Project Euler 044 is {answer}")

    # The Answer to Project Euler 044 


if __name__ == "__main__":
    main()
